# Makefile for rogue (Emscripten / WASM)
# Based on Makefile.std

PROGRAM  = ../public/wasm/rogue
O        = o
HDRS     = rogue.h extern.h score.h
OBJS1    = vers.$(O) extern.$(O) armor.$(O) chase.$(O) command.$(O) \
           daemon.$(O) daemons.$(O) fight.$(O) init.$(O) io.$(O) list.$(O) \
           mach_dep.$(O) main.$(O) mdport.$(O) misc.$(O) monsters.$(O) \
           move.$(O) new_level.$(O)
OBJS2    = options.$(O) pack.$(O) passages.$(O) potions.$(O) rings.$(O) \
           rip.$(O) rooms.$(O) save.$(O) scrolls.$(O) state.$(O) sticks.$(O) \
           things.$(O) weapons.$(O) wizard.$(O) xcrypt.$(O) wasm_pipe.$(O)
OBJS     = $(OBJS1) $(OBJS2)

CC       = emcc
# Asyncify is required for blocking terminal reads (getch)
# Emulate function pointer casts for legacy K&R compatibility (fixes signature mismatch crashes)
FEATURES = -DALLSCORES -DSCOREFILE=\"/var/games/rogomatic/rogue.scr\" -DLOCKFILE=\"/var/games/rogomatic/rogue.lck\" -D__EMSCRIPTEN__ -DROGOWEB
CFLAGS   = -g3 -O0 -std=gnu89 -Wno-deprecated-non-prototype -I../emcurses           
LIBS     = ../emcurses/emscripten/libpdcurses.a
LDFLAGS  = --pre-js ../emcurses/emscripten/termlib.js \
           -s EXIT_RUNTIME=1 -s ASYNCIFY -s ASYNCIFY_STACK_SIZE=128000 -s ALLOW_TABLE_GROWTH -s ASSERTIONS=2 \
           -s FORCE_FILESYSTEM=1 -lidbfs.js \
           -s EXPORTED_FUNCTIONS="['_main', '_my_exit', '_malloc', '_free', '_setenv', '_wasm_pipe_read', '_wasm_pipe_write']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap', 'UTF8ToString', 'stringToUTF8', 'callMain', 'run', 'addFunction', 'stackAlloc', 'stackSave', 'stackRestore', 'getValue', 'setValue', 'HEAPU8', 'FS']" \
           -s EMULATE_FUNCTION_POINTER_CASTS=1
OUTFLAG  = -o
EXE      = .js

all: $(PROGRAM).js

.c.o:
	$(CC) $(CFLAGS) $(FEATURES) -c $*.c

wasm_pipe.o: ../src/ipc/wasm_pipe.c
	$(CC) $(CFLAGS) $(FEATURES) -c ../src/ipc/wasm_pipe.c -o wasm_pipe.o
$(PROGRAM).js: $(HDRS) $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) $(LDFLAGS) $(OUTFLAG)$@

clean:
	rm -f $(OBJS) $(PROGRAM).js $(PROGRAM).wasm $(PROGRAM).data
