# Makefile for rogue (Emscripten / WASM)
# Based on Makefile.std

PROGRAM  = rogue
O        = o
HDRS     = rogue.h extern.h score.h
OBJS1    = vers.$(O) extern.$(O) armor.$(O) chase.$(O) command.$(O) \
           daemon.$(O) daemons.$(O) fight.$(O) init.$(O) io.$(O) list.$(O) \
           mach_dep.$(O) main.$(O) mdport.$(O) misc.$(O) monsters.$(O) \
           move.$(O) new_level.$(O)
OBJS2    = options.$(O) pack.$(O) passages.$(O) potions.$(O) rings.$(O) \
           rip.$(O) rooms.$(O) save.$(O) scrolls.$(O) state.$(O) sticks.$(O) \
           things.$(O) weapons.$(O) wizard.$(O) xcrypt.$(O)
OBJS     = $(OBJS1) $(OBJS2)

CC       = emcc
# Asyncify is required for blocking terminal reads (getch)
# Emulate function pointer casts for legacy K&R compatibility (fixes signature mismatch crashes)
FEATURES = -DALLSCORES -DSCOREFILE=\"rogue.scr\" -DLOCKFILE=\"rogue.lck\" -D__EMSCRIPTEN__
CFLAGS   = -g3 -O0 -s ASYNCIFY -s ASYNCIFY_STACK_SIZE=128000 -Iemcurses -s ALLOW_TABLE_GROWTH -s ASSERTIONS=2 \
           -s EMULATE_FUNCTION_POINTER_CASTS=1 -std=gnu89 -Wno-deprecated-non-prototype \
           -s EXPORTED_FUNCTIONS="['_main', '_my_exit']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap', 'UTF8ToString', 'stringToUTF8', 'callMain', 'addFunction']"
LIBS     = emcurses/emscripten/libpdcurses.a
LDFLAGS  = 
OUTFLAG  = -o
EXE      = .js

.c.o:
	$(CC) $(CFLAGS) $(FEATURES) -c $*.c

$(PROGRAM).js: $(HDRS) $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) $(LDFLAGS) $(OUTFLAG)$@

clean:
	rm -f $(OBJS) $(PROGRAM).js $(PROGRAM).wasm $(PROGRAM).data
